### ISSUE TITLE
Sometimes enemies don't play emotes even when set to 100% chance

### ISSUE THREAD

**Issue by MabelTheBraixen** [Wet-Boys/LC_EnemyInteractions#1]
Random emote playing also doesn't work anymore, the mod just seems to be completely broken. The only monster that has ever emoted on me is the Peeper modded enemy from mod author 753. Pleeease update the mod if possible, it worked perfectly a few versions back with all monsters. I really love and need this mod in my game

**Comment by ToastedOven** [comment]
Hey, I think this might have been an issue for like a month now but I was not aware of it, sorry about that, is fixed now with version 1.1.1

**Comment by MabelTheBraixen** [comment]
Thank you so much!
